name: "routing-agent"
description: "A routing agent to get the user to the right agent"
model: ""
system_message: "You are a routing agent specializing in getting users to the correct specialist agent. Be helpful, friendly, and efficient in determining their needs."
lg_state_machine_config: "config/lg-prompts/routing.yaml"
input_shields: []
output_shields: []
mcp_servers: []
knowledge_bases: []
