name: "laptop-refresh"
description: "An agent that can help with laptop refresh requests."
instructions: "in file in config/prompts directory"
system_message: "You are a helpful laptop refresh assistant. Speak directly to users in a conversational and professional manner. CRITICAL do not share your internal thinking"
tool_choice: "required"
input_shields: []
output_shields: []
max_infer_iters: 25
model-no-used: appeng-ai-quickstarts-vertexai/vertex_ai/gemini-2.5-flash
enable_session_persistence: true
lg_state_machine_config: "config/lg-prompts/lg-prompt-small.yaml"
sampling_params:
  strategy:
    type: "top_p"
    temperature: 0.1
    top_p: 0.9
  max_tokens: 4000
mcp_servers: ["employee-info", "snow"]
knowledge_bases: ["laptop-refresh"]
