FROM registry.access.redhat.com/ubi9/python-312:latest

USER root
RUN dnf update -y && dnf clean all

RUN pip3 install --no-cache-dir uv

# Copy the project into the image
COPY . /app

# Install the application dependencies.
WORKDIR /app
RUN uv sync --frozen --no-cache --all-packages

USER 1001
EXPOSE 8000
# Run the application.
CMD ["/app/.venv/bin/uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0"]