{{- if .Values.infinispan.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "self-service-agent.fullname" . }}-infinispan-config
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
data:
  infinispan.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:15.0 https://infinispan.org/schemas/infinispan-config-15.0.xsd"
        xmlns="urn:infinispan:config:15.0">
      
      <cache-container name="default" statistics="true">
        <transport cluster="{{ include "self-service-agent.fullname" . }}-cluster" stack="tcp"/>
        
        <!-- Session cache configuration -->
        <distributed-cache name="sessions"
                          mode="SYNC"
                          owners="2"
                          segments="256">
          
          <expiration lifespan="3600000"
                     max-idle="1800000"/>
          
          {{- if .Values.infinispan.persistence.enabled }}
          <persistence passivation="false">
            <soft-index-file-store>
              <data path="/opt/infinispan/server/data"/>
              <index path="/opt/infinispan/server/data"/>
            </soft-index-file-store>
          </persistence>
          {{- end }}
          
          <memory max-count="10000" when-full="REMOVE"/>
        </distributed-cache>
      </cache-container>
    </infinispan>
{{- end }}
