{{- if and .Values.requestManagement.enabled .Values.requestManagement.integrationDispatcher.enabled .Values.requestManagement.useKnativeServices }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
  annotations:
    security.istio.io/tlsMode: istio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "self-service-agent.fullname" . }}-integration-dispatcher-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["pgvector", "integration-dispatcher-secrets"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "self-service-agent.fullname" . }}-integration-dispatcher-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "self-service-agent.fullname" . }}-integration-dispatcher-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
    app: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
    version: v1
  annotations:
    # Networking configuration
    {{- if eq .Values.requestManagement.knative.serviceVisibility "cluster-local" }}
    networking.knative.dev/visibility: cluster-local
    {{- end }}
    # Service Mesh integration annotations moved to pod template level
spec:
  template:
    metadata:
      labels:
        {{- include "self-service-agent.labels" . | nindent 8 }}
        app: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
        version: v1
      annotations:
        # Auto-scaling configuration
        autoscaling.knative.dev/minScale: {{ .Values.requestManagement.integrationDispatcher.autoscaling.minScale | quote }}
        autoscaling.knative.dev/maxScale: {{ .Values.requestManagement.integrationDispatcher.autoscaling.maxScale | quote }}
        autoscaling.knative.dev/target: {{ .Values.requestManagement.integrationDispatcher.autoscaling.target | quote }}
        # Resource limits
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        # # Service Mesh sidecar configuration - disabled for Kafka dispatcher connectivity
        # sidecar.istio.io/inject: "false"
        # sidecar.istio.io/proxyCPU: "10m"
        # sidecar.istio.io/proxyMemory: "64Mi"
        # # Traffic configuration for Knative service port
        # traffic.sidecar.istio.io/includeInboundPorts: "8080"
        # traffic.sidecar.istio.io/excludeOutboundPorts: "5432,587"  # PostgreSQL, SMTP
    spec:
      containerConcurrency: 50
      timeoutSeconds: 300
      serviceAccountName: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
      containers:
      - name: integration-dispatcher
        image: {{ .Values.image.integrationDispatcher }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        # Database configuration
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: pgvector
              key: host
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: pgvector
              key: port
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pgvector
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgvector
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgvector
              key: password
        # Application configuration
        - name: LOG_LEVEL
          value: "INFO"
        - name: SQL_DEBUG
          value: "false"
        - name: EXPECTED_MIGRATION_VERSION
          value: {{ .Values.database.expectedMigrationVersion | default "001" | quote }}
        # Integration credentials
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: integration-dispatcher-secrets
              key: slack-bot-token
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: integration-dispatcher-secrets
              key: smtp-host
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: integration-dispatcher-secrets
              key: smtp-port
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: integration-dispatcher-secrets
              key: smtp-username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: integration-dispatcher-secrets
              key: smtp-password
        - name: SMTP_USE_TLS
          valueFrom:
            secretKeyRef:
              name: integration-dispatcher-secrets
              key: smtp-use-tls
        - name: FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: integration-dispatcher-secrets
              key: from-email
        - name: FROM_NAME
          valueFrom:
            secretKeyRef:
              name: integration-dispatcher-secrets
              key: from-name
        resources:
          requests:
            memory: {{ .Values.requestManagement.integrationDispatcher.resources.requests.memory }}
            cpu: {{ .Values.requestManagement.integrationDispatcher.resources.requests.cpu }}
          limits:
            memory: {{ .Values.requestManagement.integrationDispatcher.resources.limits.memory }}
            cpu: {{ .Values.requestManagement.integrationDispatcher.resources.limits.cpu }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
{{- end }}
