{{- if and .Values.requestManagement.enabled (not .Values.requestManagement.useKnativeServices) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
    app: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
    component: integration-dispatcher
spec:
  replicas: {{ .Values.requestManagement.integrationDispatcher.replicas | default 2 }}
  selector:
    matchLabels:
      {{- include "self-service-agent.selectorLabels" . | nindent 6 }}
      app: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
      component: integration-dispatcher
  template:
    metadata:
      labels:
        {{- include "self-service-agent.labels" . | nindent 8 }}
        app: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
        component: integration-dispatcher
        version: v1
      annotations:
        # Service Mesh sidecar configuration
        sidecar.istio.io/inject: "{{ .Values.requestManagement.integrationDispatcher.istio.sidecarInject }}"
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyMemory: "64Mi"
        # Traffic configuration
        traffic.sidecar.istio.io/includeInboundPorts: "8080"
        traffic.sidecar.istio.io/excludeOutboundPorts: "5432,587,9092"  # PostgreSQL, SMTP, Kafka
    spec:
      serviceAccountName: {{ include "self-service-agent.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: integration-dispatcher
        image: {{ .Values.image.integrationDispatcher }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        env:
        # Database configuration
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: pgvector
              key: host
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: pgvector
              key: port
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pgvector
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgvector
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgvector
              key: password
        - name: BROKER_URL
          value: "{{ .Values.requestManagement.knative.broker.url }}/{{ .Release.Namespace }}/{{ .Values.requestManagement.knative.broker.name }}"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PORT
          value: "8080"
        - name: HOST
          value: "0.0.0.0"
        - name: SQL_DEBUG
          value: "false"
        - name: EXPECTED_MIGRATION_VERSION
          value: {{ .Values.database.expectedMigrationVersion | default "001" | quote }}
        # Integration-specific environment variables (optional - loaded from secrets)
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "self-service-agent.fullname" . }}-integration-secrets
              key: slack-bot-token
              optional: true
        - name: SLACK_SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "self-service-agent.fullname" . }}-integration-secrets
              key: slack-signing-secret
              optional: true
        - name: EMAIL_SMTP_HOST
          value: {{ .Values.requestManagement.integrations.email.smtpHost | default "smtp.example.com" | quote }}
        - name: EMAIL_SMTP_PORT
          value: {{ .Values.requestManagement.integrations.email.smtpPort | default "587" | quote }}
        # Additional SMTP configuration from secrets (matching Knative Service)
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "self-service-agent.fullname" . }}-integration-secrets
              key: smtp-host
              optional: true
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "self-service-agent.fullname" . }}-integration-secrets
              key: smtp-port
              optional: true
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "self-service-agent.fullname" . }}-integration-secrets
              key: smtp-username
              optional: true
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "self-service-agent.fullname" . }}-integration-secrets
              key: smtp-password
              optional: true
        - name: SMTP_USE_TLS
          valueFrom:
            secretKeyRef:
              name: {{ include "self-service-agent.fullname" . }}-integration-secrets
              key: smtp-use-tls
              optional: true
        - name: FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: {{ include "self-service-agent.fullname" . }}-integration-secrets
              key: from-email
              optional: true
        - name: FROM_NAME
          valueFrom:
            secretKeyRef:
              name: {{ include "self-service-agent.fullname" . }}-integration-secrets
              key: from-name
              optional: true
        resources:
          requests:
            memory: {{ .Values.requestManagement.integrationDispatcher.resources.requests.memory }}
            cpu: {{ .Values.requestManagement.integrationDispatcher.resources.requests.cpu }}
          limits:
            memory: {{ .Values.requestManagement.integrationDispatcher.resources.limits.memory }}
            cpu: {{ .Values.requestManagement.integrationDispatcher.resources.limits.cpu }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
    app: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
    component: integration-dispatcher
spec:
  type: ClusterIP
  selector:
    {{- include "self-service-agent.selectorLabels" . | nindent 4 }}
    app: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
    component: integration-dispatcher
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
---
{{- if .Values.requestManagement.integrationDispatcher.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
    app: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
    component: integration-dispatcher
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "self-service-agent.fullname" . }}-integration-dispatcher
  minReplicas: {{ .Values.requestManagement.integrationDispatcher.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.requestManagement.integrationDispatcher.autoscaling.maxReplicas | default 5 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.requestManagement.integrationDispatcher.autoscaling.targetCPUUtilization | default 70 }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.requestManagement.integrationDispatcher.autoscaling.targetMemoryUtilization | default 80 }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
{{- end }}
{{- end }}
