{{- if and .Values.requestManagement.enabled .Values.requestManagement.knative.eventing.enabled .Values.requestManagement.knative.kafka.enabled }}
---
# KnativeKafka for self-service-agent namespace
apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: {{ .Values.requestManagement.knative.kafka.name | default "self-service-agent-kafka-eventing" }}
  namespace: knative-eventing
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
spec:
  # Kafka Channel configuration
  channel:
    enabled: {{ .Values.requestManagement.knative.kafka.channel.enabled | default false }}
    bootstrapServers: "{{ .Values.requestManagement.kafka.name }}-kafka-bootstrap.{{ .Release.Namespace }}.svc:9092"
    authSecretName: ""
    authSecretNamespace: ""
    # Channel-specific configurations (commented out - not supported in current KnativeKafka CRD)
    # config:
    #   # Default number of partitions for channels
    #   default.partitions: {{ .Values.requestManagement.knative.kafka.channel.defaultPartitions | default 3 }}
    #   # Default replication factor for channels
    #   default.replication.factor: {{ .Values.requestManagement.kafka.config.defaultReplicationFactor }}
    #   # Retention policy for channel topics
    #   retention.ms: {{ .Values.requestManagement.knative.kafka.channel.retentionMs | default "604800000" }}  # 7 days
    #   # Cleanup policy
    #   cleanup.policy: "delete"
    #   # Compression type
    #   compression.type: {{ .Values.requestManagement.knative.kafka.channel.compressionType | default "snappy" }}

  # Kafka Broker configuration (for Knative Kafka Broker, different from your Knative Broker)
  broker:
    enabled: {{ .Values.requestManagement.knative.kafka.broker.enabled | default false }}
    {{- if .Values.requestManagement.knative.kafka.broker.enabled }}
    defaultConfig:
      bootstrapServers: "{{ .Values.requestManagement.kafka.name }}-kafka-bootstrap.{{ .Release.Namespace }}.svc:9092"
      authSecretName: ""
      numPartitions: {{ .Values.requestManagement.knative.kafka.broker.numPartitions | default 10 }}
      replicationFactor: {{ .Values.requestManagement.kafka.config.defaultReplicationFactor }}
      # Topic configuration for broker (moved to top level - config nested under defaultConfig is not supported)
      retention.ms: {{ .Values.requestManagement.knative.kafka.broker.retentionMs | default "2592000000" }}  # 30 days
      cleanup.policy: "delete"
      compression.type: {{ .Values.requestManagement.knative.kafka.broker.compressionType | default "snappy" }}
    {{- end }}

  # Kafka Source configuration
  source:
    enabled: {{ .Values.requestManagement.knative.kafka.source.enabled | default false }}

  # Kafka Sink configuration  
  sink:
    enabled: {{ .Values.requestManagement.knative.kafka.sink.enabled | default false }}

  # High availability configuration
  high-availability:
    replicas: {{ .Values.requestManagement.knative.kafka.replicas | default 1 }}

  # Logging configuration
  logging:
    level: {{ .Values.requestManagement.knative.kafka.logLevel | default "INFO" }}
    
  # Resource configuration for Knative Kafka components (commented out - not supported in current KnativeKafka CRD)
  # resources:
  #   requests:
  #     memory: {{ .Values.requestManagement.knative.kafka.resources.requests.memory | default "256Mi" }}
  #     cpu: {{ .Values.requestManagement.knative.kafka.resources.requests.cpu | default "100m" }}
  #   limits:
  #     memory: {{ .Values.requestManagement.knative.kafka.resources.limits.memory | default "512Mi" }}
  #     cpu: {{ .Values.requestManagement.knative.kafka.resources.limits.cpu | default "500m" }}

  # Security configuration (commented out - not supported in current KnativeKafka CRD)
  # security:
  #   securityProtocol: {{ .Values.requestManagement.knative.kafka.security.protocol | default "PLAINTEXT" }}
  #   {{- if .Values.requestManagement.knative.kafka.security.sasl.enabled }}
  #   sasl:
  #     mechanism: {{ .Values.requestManagement.knative.kafka.security.sasl.mechanism }}
  #     user: {{ .Values.requestManagement.knative.kafka.security.sasl.user }}
  #     secretName: {{ .Values.requestManagement.knative.kafka.security.sasl.secretName }}
  #     secretKey: {{ .Values.requestManagement.knative.kafka.security.sasl.secretKey }}
  #   {{- end }}
{{- end }}
