# step 1 install the dependencies
FROM registry.access.redhat.com/ubi9/python-312:latest as builder

USER root
RUN dnf update -y && dnf clean all
RUN pip3 install --no-cache-dir uv

WORKDIR /app
COPY . .
RUN uv sync --frozen --no-cache

# step 2 build the final image with just what is needed
FROM registry.access.redhat.com/ubi9/python-312-minimal:latest

WORKDIR /app
COPY --from=builder /app/.venv /app/.venv
COPY config/ ./config
COPY src/. ./src
COPY script/ ./script

# Set up paths
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app/src:$PYTHONPATH"

# Drop privileges
USER 1001

# Command to run the application using the virtual environment
CMD ["python", "script/register_agents.py"]
