name: Initialize cluster and deploy application
description: Initialize cluster and deploy application

inputs:
  namespace:
    description: The namespace to deploy the application to
    required: false
    default: test
  llm:
    description: The LLM to use
    required: true
  llm_id:
    description: The LLM ID
    required: true
  llm_url:
    description: The LLM URL
    required: true

runs:
  using: composite
  steps:

    - name: Install Kind
      run: go install sigs.k8s.io/kind@v0.30.0
      shell: bash

    - name: Create Kind Cluster
      run: bash ./scripts/ci/kind-with-registry.sh
      shell: bash

    - name: Helm install Toolhive CRDs
      run: |
        helm repo add toolhive https://stacklok.github.io/toolhive
        helm repo update
        helm install toolhive-crds toolhive/toolhive-operator-crds --version 0.0.24
      shell: bash

    - name: Helm Depend
      run: make helm-depend
      shell: bash

    - name: Build local images
      run: make build-all-images REGISTRY=localhost:5001
      shell: bash

    - name: Push local images to the local registry
      run: make push-all-images REGISTRY=localhost:5001 PUSH_EXTRA_AGRS="--tls-verify=false"
      shell: bash  

    - name: Helm Install (using local registry)
      run: make helm-install-test NAMESPACE=${{inputs.namespace}} REGISTRY=localhost:5001 LLM=${{inputs.llm}} LLM_ID=${{inputs.llm_id}} LLM_URL=${{inputs.llm_url}} LLM_API_TOKEN=$LLM_API_TOKEN EXTRA_HELM_ARGS="--set requestManagement.externalAccess.enabled=false"
      shell: bash
