{{- if .Values.jailbreakDetect.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ngc-pull-secret
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"nvcr.io":{"username":"$oauthtoken","password":%q}}}` .Values.ngcApiKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ngc-api-key-secret
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  NGC_API_KEY: {{ .Values.ngcApiKey | quote }}
{{- end }}
