# State Machine Configuration for Laptop Refresh Agent
# Each state defines its behavior, prompts, and transition conditions

# Global settings
settings:
  initial_state: "lookup_employee"
  terminator_env_var: "AGENT_MESSAGE_TERMINATOR"
  agent_name: "laptop-refresh"
  terminal_state: "end"
  empty_response_retry_count: 3

# State structure definition - completely configurable
state_schema:
  # Business logic fields
  business_fields:
    employee_info:
      type: "dict"
      description: "Employee information from lookup"
      default: null
    laptop_eligibility:
      type: "dict"
      description: "Laptop refresh eligibility assessment"
      default: null
    eligibility_status:
      type: "string"
      description: "Eligibility classification result (ELIGIBLE, NOT, UNCLEAR)"
      default: null
    selected_laptop:
      type: "string"
      description: "User's selected laptop model"
      default: null
    selected_laptop_details:
      type: "dict"
      description: "Full details of the selected laptop"
      default: null
    laptop_options:
      type: "dict"
      description: "Available laptop options shown to user"
      default: null
    ticket_created:
      type: "boolean"
      description: "Whether ServiceNow ticket was created"
      default: false
    user_wants_to_proceed:
      type: "boolean"
      description: "User's decision to proceed with process"
      default: null

# State definitions
states:
  # State 1: Lookup Employee Information
  lookup_employee:
    type: "llm_processor"
    temperature: 0.3  # Factual lookup, should be consistent
    allowed_tools: [ "get_employee_laptop_info" ]
    prompt: |
      You are a helpful laptop refresh assistant. CRITICAL: look up the laptop information for the authenticated user by using the get_employee_laptop_info tool. Provide their current laptop details including: name, region, purchase date, laptop age, model, and serial number.
      If the user is not found, explain that their information was not found in the database.
    transitions:
      success: "classify_lookup_result"
    data_storage:
      employee_info: "llm_response"

  # State 1c: Classify Lookup Result
  classify_lookup_result:
    type: "llm_processor"
    temperature: 0.1  # Very deterministic classification
    uses_tools: "No"
    prompt: |
      Think step by step and use no tools
      Analyze this employee lookup response: "{employee_info.response}"

      Classify the result as SUCCESS, NOT_FOUND, or ERROR:
      - SUCCESS: if employee information was found (contains details like name, region, laptop model, etc.)
      - NOT_FOUND: if the employee ID was not found in the database
      - ERROR: if there was a system error or unclear response

      Respond with only the classification: SUCCESS, NOT_FOUND, or ERROR
    response_analysis:
      conditions:
        - name: "success"
          trigger_phrases: ["SUCCESS"]
          actions:
            - type: "transition"
              target: "check_eligibility"
        - name: "not_found"
          trigger_phrases: ["NOT_FOUND"]
          actions:
            - type: "add_message"
              message: "I'm sorry, your information was not found in our database. Please contact IT support for assistance."
            - type: "transition"
              target: "end"
        - name: "error"
          trigger_phrases: ["ERROR"]
          actions:
            - type: "add_message"
              message: "I encountered an issue looking up your information. Please try again or contact IT support."
            - type: "transition"
              target: "end"
      default_transition: "end"

  # State 2: Check Eligibility
  check_eligibility:
    type: "llm_processor"
    temperature: 0.4  # Mix of factual lookup + conversational response
    uses_mcp_tools: "No"
    prompt: |
      You have the employee information: {employee_info.response}

      Search the laptop refresh knowledge base for the company's laptop refresh policy and determine if this employee is eligible for a laptop replacement. Specifically:

      1. Look up the corporate laptop refresh policy to find the refresh cycle/interval
      2. Compare the users current laptop age against the policy requirements
      3. Provide a clear summary to the user including their laptop details and eligibility status. The summary should speak directly to the user.
      4. Include their current laptop details (name, region, purchase date, laptop age, model, serial number)
      5. Clearly state whether they can request a replacement today and explain the policy
      6. If eligible ask if they would like to proceed to reviewing the laptop options. Do not ask for any additional information.

      Be conversational and helpful.
    transitions:
      success: "classify_eligibility_result"
    data_storage:
      laptop_eligibility: "llm_response"

  # State 2a: Classify Eligibility Result
  classify_eligibility_result:
    type: "llm_processor"
    temperature: 0.1  # Very deterministic classification
    uses_tools: "No"
    prompt: |
      Think step by step and use not tools
      This is the summary of the user's eligibility: "{laptop_eligibility.response}"

      If the response says the user is eligible for a laptop replacement, respond: ELIGIBLE
      If the response says the user is not eligible, respond: NOT
      If unclear, respond: UNCLEAR

      Respond with only one word: ELIGIBLE, NOT, or UNCLEAR
    response_analysis:
      conditions:
        - name: "eligible"
          trigger_phrases: ["ELIGIBLE"]
          actions:
            - type: "set_field"
              field_name: "eligibility_status"
              value: "ELIGIBLE"
            - type: "add_message"
              message: "{laptop_eligibility.response}"
            - type: "transition"
              target: "waiting_proceed_confirmation"
        - name: "not_eligible"
          trigger_phrases: ["NOT"]
          actions:
            - type: "set_field"
              field_name: "eligibility_status"
              value: "NOT_ELIGIBLE"
            - type: "add_message"
              message: "{laptop_eligibility.response}"
            - type: "transition"
              target: "waiting_ineligible_user_input"
        - name: "unclear"
          trigger_phrases: ["UNCLEAR"]
          actions:
            - type: "set_field"
              field_name: "eligibility_status"
              value: "UNCLEAR"
            - type: "add_message"
              message: "I need to review your eligibility status again. Please contact IT support for further assistance."
            - type: "transition"
              target: "end"
      default_transition: "end"

  # State 3: Waiting for Ineligible User Input
  waiting_ineligible_user_input:
    type: "waiting"
    transitions:
      user_input: "classify_ineligible_user_intent"

  # State 3a: Classify Ineligible User Intent
  classify_ineligible_user_intent:
    type: "intent_classifier"
    temperature: 0.2  # Deterministic intent classification
    uses_tools: "No"
    intent_prompt: |
      Analyze the user's message and determine their intent. The user said: "{user_input}"

      Context: This user is NOT currently eligible for a laptop replacement under standard policy.

      Classify the user's intent as one of the following:
      1. FAREWELL - User wants to end the conversation (goodbye, bye, thanks, etc.)
      2. PROCEED_ANYWAY - User wants to see laptop options despite being ineligible (proceed, show options, I want to see, etc.)
      3. GENERAL_QUESTION - User has questions about policy or general assistance

      Respond with only the classification: FAREWELL, PROCEED_ANYWAY, or GENERAL_QUESTION
    intent_actions:
      FAREWELL:
        response: "Thank you for using the laptop refresh service. Have a great day!"
        next_state: "end"
      PROCEED_ANYWAY:
        response: "I understand you'd like to proceed. While you're not currently eligible under the standard policy, I can show you the available options. Please note that any request would need special approval and may be subject to additional justification requirements. Would you like to see the available laptop options?"
        data_storage:
          user_wants_to_proceed: true
        next_state: "select_laptop"
      GENERAL_QUESTION:
        prompt: |
          Previously retrieved information on laptop eligibility: {laptop_eligibility.response}

          The user said '{user_input}'. This user is NOT currently eligible for a laptop replacement under standard policy but is allowed to proceed anyway as long as they undertand that the request may be rejected or require additional approval. Provide a helpful response about laptop refresh policies or general assistance. If they're asking about their eligibility again, remind them they are not currently eligible and when they will become eligible.
        next_state: "waiting_ineligible_user_input"

  # State 4: Waiting for Proceed Confirmation
  waiting_proceed_confirmation:
    type: "waiting"
    transitions:
      user_input: "proceed_confirmation"

  # State 4a: Proceed Confirmation
  proceed_confirmation:
    type: "intent_classifier"
    temperature: 0.2  # Deterministic yes/no classification
    uses_tools: "No"
    intent_prompt: |
      The user was asked if they want to proceed with reviewing laptop options. They responded: "{user_input}"

      Classify their response as one of the following:
      1. YES - User wants to proceed (yes, sure, okay, proceed, continue, etc.)
      2. NO - User does not want to proceed or wants to end conversation (no, cancel, stop, bye, etc.)
      3. UNCLEAR - Response is ambiguous or unclear

      Respond with only the classification: YES, NO, or UNCLEAR
    intent_actions:
      "YES":
        next_state: "select_laptop"
        data_storage:
          user_wants_to_proceed: true
      "NO":
        response: "No problem! If you change your mind or need help with anything else, feel free to ask."
        next_state: "end"
        data_storage:
          user_wants_to_proceed: false
      "UNCLEAR":
        response: "Please let me know if you'd like to proceed with reviewing the available laptop options (yes/no)."
        next_state: "waiting_proceed_confirmation"

  # State 5: Select Laptop
  select_laptop:
    type: "llm_processor"
    temperature: 0.2  # Mix of factual info + conversational presentation
    uses_mcp_tools: "No"
    conditional_prompts:
      - condition: "user_is_ineligible"
        check_field: "eligibility_status"
        check_phrases: ["NOT"]
        prompt: |
          Previously retrieved information on laptop eligibility: {laptop_eligibility.response}

          The user wants to see laptop options based on\n {employee_info.response}\n even though they are not currently eligible under standard policy. Search the laptop refresh knowledge base and present them with all available laptop models based on their region. CRITICAL Include detailed specifications for each option and ask them to choose one specific laptop. CRITICAL only show them the numbered list of laptops for their region. CRITICAL do not show any laptops that are not listed for their region

          IMPORTANT: Include a warning that they are not currently eligible under standard policy and any request would require special approval and justification.

          Ask them to choose one specific laptop if they wish to proceed with a special request.

          Only use information from the knowledge base - don't add external details.
      - condition: "default"
        prompt: |
          The user wants to see their laptop options based on {employee_info.response}.\n Search the laptop refresh knowledge base and present them with numbered list of all available laptop models based on their region. CRITICAL Include detailed specifications for each option and ask them to choose one specific laptop. CRITICAL only show them the list of laptops for their region.

          Only use information from the knowledge base - don't add external details.
    transitions:
      success: "waiting_laptop_selection"
    data_storage:
      laptop_options: "llm_response"

  # State 6: Waiting for Laptop Selection
  waiting_laptop_selection:
    type: "waiting"
    transitions:
      user_input: "classify_laptop_selection"

  # State 6a: Classify Laptop Selection
  classify_laptop_selection:
    type: "intent_classifier"
    temperature: 0.2  # Deterministic selection validation
    uses_tools: "No"
    intent_prompt: |
      The user said: "{user_input}"

      Based on the laptop options "{laptop_options.response}", determine if they made a valid laptop selection:
      - VALID_SELECTION: User mentioned a specific laptop model, number, or clear selection
      - INVALID_SELECTION: User's choice is clearly invalid or nonsensical
      - UNCLEAR: User's response is unclear or doesn't contain a laptop selection

      Respond with only: VALID_SELECTION, INVALID_SELECTION, or UNCLEAR
    intent_actions:
      "VALID_SELECTION":
        next_state: "confirm_laptop_selection"
        data_storage:
          selected_laptop: "{user_input}"
      "INVALID_SELECTION":
        response: "I don't see that option in the available laptop list. Please choose one of the specific laptop models I showed you earlier."
        next_state: "waiting_laptop_selection"
      "UNCLEAR":
        response: "Please specify which laptop model you'd like to select from the options I provided."
        next_state: "waiting_laptop_selection"

  # State 6b: Confirm Laptop Selection with Full Details
  confirm_laptop_selection:
    type: "llm_processor"
    temperature: 0.2  # Mix of factual lookup + conversational confirmation
    uses_tools: "No"
    prompt: |
      The user selected: "{selected_laptop}"

      From the following laptop options, find the details for the user's selection and provide them with the complete specifications:

      {laptop_options.response}

      Then ask them to confirm that is the correct laptop and that they would like you to create a Service Now ticket. CRITICAL do not ask for any information other than if they would like you to create the service now ticket.
    transitions:
      success: "waiting_ticket_confirmation"
    data_storage:
      selected_laptop_details: "llm_response"

  # State 7: Waiting for Ticket Confirmation
  waiting_ticket_confirmation:
    type: "waiting"
    transitions:
      user_input: "classify_ticket_confirmation"

  # State 7a: Classify Ticket Confirmation
  classify_ticket_confirmation:
    type: "intent_classifier"
    temperature: 0.2  # Deterministic yes/no classification
    uses_tools: "No"
    intent_prompt: |
      The user was asked if they want to create a ServiceNow ticket for their laptop refresh request. They responded: "{user_input}"

      Classify their response as one of the following:
      1. YES - User wants to create the ticket (yes, proceed, create, sure, okay, etc.)
      2. NO - User does not want to create the ticket (no, cancel, stop, etc.)
      3. UNCLEAR - Response is ambiguous or unclear

      Respond with only the classification: YES, NO, or UNCLEAR
    intent_actions:
      "YES":
        uses_tools: "Yes"
        allowed_tools: [ "open_laptop_refresh_ticket" ]
        prompt: |
          You have the employee information: {employee_info.response}
          Selected Laptop details: {selected_laptop_details}
          Create a ServiceNow ticket for the authenticated user requesting laptop: {selected_laptop} by calling the open_laptop_refresh_ticket tool with "None" as the employee_id parameter, the user's name from the employee info, the laptop information, and business justification "agent submission". CRITICAL use the open_laptop_refresh_ticket tool to create the ticket.
          Tell the user their ticket number after creation.
        next_state: "end"
        data_storage:
          ticket_created: true
      "NO":
        prompt: "Acknowledge that the user doesn't want to create a ticket and offer to help with anything else."
        next_state: "end"
      "UNCLEAR":
        prompt: "The user said '{user_input}' when asked about creating a ticket. Ask them to clarify: do they want to create the ServiceNow ticket? (yes/no)"
        next_state: "waiting_ticket_confirmation"

  # End state
  end:
    type: "terminal"
    reset_behavior:
      reset_state: "lookup_employee"  # Start with employee lookup using authoritative user ID
      clear_data: ["messages", "employee_info", "laptop_eligibility", "selected_laptop", "selected_laptop_details", "laptop_options", "eligibility_status", "ticket_created", "current_state", "user_wants_to_proceed"]
