name: 'Build and Push Images'
description: 'Build and push Docker images with versioning'

inputs:
  branch:
    description: 'Target branch (main or dev)'
    required: true
  registry:
    description: 'Docker registry URL'
    required: true
    default: 'quay.io/ecosystem-appeng'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      shell: bash

    - name: Extract version from Makefile
      id: version
      run: |
        RAW_VERSION=$(make version)
        # Append -dev for dev branch (only in BASE_VERSION, not VERSION_WITH_COMMIT)
        if [[ "${{ inputs.branch }}" == "main" ]]; then
          BASE_VERSION="${RAW_VERSION}"
        else
          BASE_VERSION="${RAW_VERSION}-dev"
        fi
        VERSION_WITH_COMMIT="${RAW_VERSION}-${{ github.sha }}"
        echo "base_version=${BASE_VERSION}" >> $GITHUB_OUTPUT
        echo "version_with_commit=${VERSION_WITH_COMMIT}" >> $GITHUB_OUTPUT

        # Build versions list - add latest only for main branch
        VERSIONS="${BASE_VERSION} ${VERSION_WITH_COMMIT}"
        if [[ "${{ inputs.branch }}" == "main" ]]; then
          VERSIONS="${VERSIONS} latest"
          echo "Adding 'latest' tag for main branch"
        else
          VERSIONS="${VERSIONS} dev"
          echo "Adding 'dev' tag for dev branch"
        fi

        echo "versions=${VERSIONS}" >> $GITHUB_OUTPUT
        echo "Base version: ${BASE_VERSION}"
        echo "Version with commit: ${VERSION_WITH_COMMIT}"
        echo "All versions: ${VERSIONS}"
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Quay.io
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.6.17"
        python-version: "3.12"

    - name: Build all Images
      run: |
        IFS=' ' read -ra VERSIONS <<< "${{ steps.version.outputs.versions }}"
        for version in "${VERSIONS[@]}"; do
          echo "Building images with version: ${version}"
          VERSION="${version}" make build-all-images
        done
      shell: bash

    - name: Push all Images
      run: |
        IFS=' ' read -ra VERSIONS <<< "${{ steps.version.outputs.versions }}"
        for version in "${VERSIONS[@]}"; do
          echo "Pushing images with version: ${version}"
          VERSION="${version}" make push-all-images
        done
      shell: bash

